### 디폴트 값이 asc 값 변경은 뒤에 *?order=desc* 추가하면됨.
GET http://localhost:8080/api/todo
content-type: application/json

###
GET http://localhost:8080/api/todo/1

###
POST http://localhost:8080/api/todo
content-type: application/json

{
    "title": "Test입니다~",
    "dueDate":"2025-03-10T14:00:00",
    "status": "PENDING"
}

###
PUT http://localhost:8080/api/todo/7
content-type: application/json

{
    "title": "PUT_TEST입니다~",
    "description": "PUT_TEST 할 일입니다.",
    "dueDate":"2025-03-21T14:00:00",
    "status": "COMPLETED"
}

###
PATCH http://localhost:8080/api/todo/6
content-type: application/json

{
    "status": "PENDING"
}

###
DELETE http://localhost:8080/api/todo/6

### Event가져오는 API
GET http://localhost:8080/api/event
content-type: application/json

###
GET http://localhost:8080/api/event/1

###
POST http://localhost:8080/api/event
content-type: application/json

{
    "title": "Test입니다~",
    "description": "Test 일정 입니다.",
    "startDateTime":"2025-03-10T14:00:00",
    "endDateTime":"2025-03-10T14:00:00",
    "location":"회의실B"
}

###
PUT http://localhost:8080/api/event/1
content-type: application/json

{
    "title": "Test입니다~",
    "description": "Test 일정 입니다.",
    "startDateTime":"2025-03-10T14:00:00",
    "endDateTime":"2025-03-10T14:00:00",
    "location":"회의실B"
}

### 여기서 뭐를 받아서 수정할지 고민사항.
# PATCH http://localhost:8080/api/event/1
# content-type: application/json

# {
#     "title": "Test입니다~",
#     "description": "Test 일정 입니다.",
#     "startDateTime":"2025-03-10T14:00:00",
#     "endDateTime":"2025-03-10T14:00:00",
#     "location":"회의실B"
# }

###
DELETE http://localhost:8080/api/event/4

### 모든 설명 조회
GET http://localhost:8080/api/todo/descriptions

### 특정 todoId로 모든 설명 조회
GET http://localhost:8080/api/todo/descriptions/1

### 설명 추가(PathVariable로 todoId값 받음)
POST http://localhost:8080/api/todo/descriptions/1
Content-Type: application/json

{
    "description" : ""
}

### id로 설명 수정(PathVariable로 todoId값 받음)
PUT http://localhost:8080/api/todo/descriptions/13
content-type: application/json

{
    "description": "Test 설명 수정 입니다."
}

### 설명 삭제(PathVariable로 todoId값 받음)
DELETE  http://localhost:8080/api/todo/descriptions/1

### 메일보내기
POST http://localhost:8080/api/todo/share/mail
content-type: application/json

{
    "email": "qqq4118@naver.com",
    "todoIds": 
    [
    1,3
    ]

}

